// <auto-generated />
using System;
using JuanAraujo_Examen1P.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JuanAraujo_Examen1P.Migrations
{
    [DbContext(typeof(JuanAraujo_Examen1PContext))]
    [Migration("20231025132604_CambiosTabla1")]
    partial class CambiosTabla1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JuanAraujo_Examen1P.Models.JuanAraujo_tabla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("JaFechaCita")
                        .HasColumnType("datetime2");

                    b.Property<string>("JaName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("JaTieneCita")
                        .HasColumnType("bit");

                    b.Property<decimal>("JaValorCita")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("JuanAraujo_tabla");
                });
#pragma warning restore 612, 618
        }
    }
}
